/* eslint-disable import/prefer-default-export */
export const en = {
  header_services: 'Services',
  chatpage_send: 'Send',
  chatpage_nolog: 'Log in to use the chat application.',
  header_users: 'Users',
  header_weather: 'Weather App',
  header_space: 'SpaceX API',
  header_signed: 'Signed in as: ',
  header_logout: 'Logout',
  loadingicon: 'Loading...',
  login_username: 'Username',
  login_password: 'Password',
  login_login: 'Login',
  login_cancel: 'Cancel',
  mainpage_nolog_h1: 'Hey there! ;)',
  mainpage_nolog_p: 'Please log in to gain access to the services.',
  mainpage_title: 'App Mashup!',
  mainpage_h5: `Ever wanted one place with all the necessary tools to socialize,
  be informed about weather and get knowledge about SpaceX missions?
  Look no further!`,
  mainpage_li1: 'Socialize using the chat app.',
  mainpage_li2: 'Check out the weather forecast. World wide.',
  mainpage_li3: 'Space X -missions. The past and the future.',
  mainpage_carousel1_h3: 'Chat like no tomorrow',
  mainpage_carousel1_p: 'Limited to people on your friendlist.',
  mainpage_carousel2_h3: 'SPACE X -missions',
  mainpage_carousel2_p: 'List of upcoming flights.',
  mainpage_carousel3_h3: 'Weather forecast',
  mainpage_carousel3_p: 'Make plans with precision.',
  sc_c1_header: 'Chat Application',
  sc_c1_title: 'Socialize',
  sc_c1_p1: 'Find people.',
  sc_c1_p2: 'Add them to your friendlist.',
  sc_c1_p3: 'Chat away!',
  sc_c1_button: 'Chat App',
  sc_c2_header: 'Weather Application',
  sc_c2_title: 'Weather',
  sc_c2_text: `Choose the desired country. The app shows the weather forecast
  of the country&apos;s capital city.`,
  sc_c2_button: 'Weather App',
  sc_c3_title: 'SpaceX missions',
  sc_c3_text: `Check out all the SpaceX -missions that have happened or will
  happen.`,
  space_nolog: 'Log in to use the SpaceX API!',
  space_h1: 'Space X Missions',
  space_filter1: 'Rocket',
  space_filter2: 'Order',
  space_filter2_1: 'Descending',
  space_filter2_2: 'Ascending',
  space_filter3: 'Scope',
  space_filter3_1: 'All',
  space_filter3_2: 'Upcoming',
  space_accordion1: 'Description',
  space_accordion2: 'Rocket',
  space_accordion3: 'Launch site',
  space_accordion4: 'Countdown',
  space_filter_fail: 'No matches',
  space_days: 'd',
  space_hours: 'h',
  space_minutes: 'm',
  space_seconds: 's',
  space_expired: 'Expired',
  toggle_log: 'Log in',
  toggle_sign: 'Sign up',
  userpage_nolog: 'Log in to see the user profile.',
  userpage_friends: 'Friends:',
  userpage_username: 'Username',
  usersearch_form_label: 'Search with username:',
  usersearch_form_button: 'Clear',
  usersearch_action_add: 'Add friend',
  usersearch_action_remove: 'Remove',
  weather_nolog: 'Log in to use the weather app!',
  weather_country: 'Country',
  weather_capital: 'Capital',
  Mon: 'Mon',
  Tue: 'Tue',
  Wed: 'Wed',
  Thu: 'Thu',
  Fri: 'Fri',
  Sat: 'Sat',
  Sun: 'Sun',
  weather_avg: 'Avg:',
  msg_couldnt_remove: `The message couldn't be removed.`,
  welcome: 'Welcome',
  slide1: 'First slide',
  slide2: 'Second slide',
  slide3: 'Third slide',
  signup_success: 'Signed up successfully as',
  space_details: 'Mission details',
  chat_started: 'Chat started.',
  userpage_posts: 'Posts:',
  userpage_level: 'Level:',
  friend_added: 'Friend added.',
  clear: 'Clear',
};
