/* eslint-disable import/prefer-default-export */
export const fi = {
  header_services: 'Palvelut',
  chatpage_nolog: 'Kirjaudu sisään käyttääksesi chat-toimintoa.',
  header_users: 'Käyttäjät',
  header_weather: 'Sää-sovellus',
  header_space: 'SpaceX API',
  header_signed: 'Kirjautuneena: ',
  header_logout: 'Kirjaudu ulos',
  chatpage_send: 'Lähetä',
  loadingicon: 'Ladataan...',
  login_username: 'Käyttäjänimi',
  login_password: 'Salasana',
  login_login: 'Kirjaudu',
  login_cancel: 'Peruuta',
  mainpage_nolog_h1: 'Hei siellä! ;)',
  mainpage_nolog_p: 'Kirjaudu sisään nähdäksesi palvelutarjonnan.',
  mainpage_title: 'App Mashup!',
  mainpage_h5: `Oletko koskaan kaivannut yhtä paikkaa, 
  josta löydät kaikki tarpeelliset työkalut viestittelyyn, 
  säätietojen hakemiseen sekä SpaceX-operaatioiden tutkimiseen?
  Etsintä on ohi!`,
  mainpage_li1: 'Sosialisoidu käyttämällä chat-sovellusta.',
  mainpage_li2: 'Tarkasta sääennusteet. Maailmanlaajuisesti',
  mainpage_li3: 'Space X -tehtävät. Menneet sekä tulevat.',
  mainpage_carousel1_h3: 'Viestittele yötä päivää',
  mainpage_carousel1_p: 'Rajoitettu ystävälistallasi oleviin käyttäjiin.',
  mainpage_carousel2_h3: 'SPACE X -tehtävät',
  mainpage_carousel2_p: 'Tietoja tulevista ja menneistä tehtävistä.',
  mainpage_carousel3_h3: 'Sääennusteet',
  mainpage_carousel3_p: 'Tee suunnitelmia tarkkuudella.',
  sc_c1_header: 'Chat-sovellus',
  sc_c1_title: 'Sosialisoidu',
  sc_c1_p1: 'Löydä ihmisiä.',
  sc_c1_p2: 'Lisää heidät ystävälistallesi.',
  sc_c1_p3: 'Chattaile pois!',
  sc_c2_header: 'Sää-sovellus',
  sc_c1_button: 'Chat App',
  sc_c2_button: 'Sää-sovellus',
  sc_c2_title: 'Sää',
  sc_c2_text: `Valitse haluttu maa. 
  Sovellus kertoo sinulle kyseisen maan pääkaupungin sääennusteen.`,
  sc_c3_title: 'SpaceX operaatiot',
  sc_c3_text: `Tutki kaikkia menneitä sekä tulevia SpaceX -tehtäviä.`,
  space_nolog: 'Log in to use the SpaceX API!',
  space_h1: 'SpaceX-tehtävät',
  space_filter1: 'Raketti',
  space_filter2: 'Järjestys',
  space_filter2_1: 'Laskeva',
  space_filter2_2: 'Nouseva',
  space_filter3: 'Laajuus',
  space_filter3_1: 'Kaikki',
  space_filter3_2: 'Tulevat',
  space_accordion1: 'Kuvaus',
  space_accordion2: 'Raketti',
  space_accordion3: 'Laukaisupaikka',
  space_accordion4: 'Lähtölaskenta',
  space_filter_fail: 'Ei osumia',
  space_days: 'pv',
  space_hours: 't',
  space_minutes: 'm',
  space_seconds: 's',
  space_expired: 'Vanhentunut',
  toggle_log: 'Kirjaudu',
  toggle_sign: 'Liity',
  userpage_nolog: 'Kirjaudu sisään nähdäksesi profiilisivun.',
  userpage_friends: 'Ystävät:',
  userpage_username: 'Käyttäjänimi',
  usersearch_form_label: 'Etsi käyttäjänimellä:',
  usersearch_form_button: 'Tyhjennä',
  usersearch_action_add: 'Lisää ystävä',
  usersearch_action_remove: 'Poista',
  weather_nolog: 'Kirjaudu sisään käyttääksesi Sää-sovellusta.',
  weather_country: 'Maa',
  weather_forecast_capital: 'Pääkaupunki',
  Mon: 'Ma',
  Tue: 'Ti',
  Wed: 'Ke',
  Thu: 'To',
  Fri: 'Pe',
  Sat: 'La',
  Sun: 'Su',
  weather_avg: 'Ka:',
  msg_couldnt_remove: `Viestiä ei voitu poistaa.`,
  welcome: 'Tervetuloa',
  slide1: 'Ensimmäinen kortti',
  slide2: 'Toinen kortti',
  slide3: 'Kolmas kortti',
  signup_success: 'Rekisteröidyit hyväksytysti nimellä',
  space_details: 'Yksityiskohdat',
  chat_started: 'Chat aloitettu.',
  userpage_posts: 'Viestit:',
  userpage_level: 'Taso:',
  friend_added: 'Ystävä lisätty.',
  clear: 'Tyhjennä',
  friend_removed: 'Ystävä poistettu.',
};
